### ISSUE TITLE
macOS build issues

### ISSUE THREAD

**Issue by cyrush** [LLNL/raja-suite-tutorial#27]
```
git clone --recursive  https://github.com/LLNL/raja-suite-tutorial.git
cmake -B build -S raja-suite-tutorial
cmake --build build

```

Two issues:

1.
malloc.h not found:

```
/Users/harrison37/Work/2024.08.13.raja.tutorial/raja-suite-tutorial/Intermediate_Tutorial/00-BASE/fractal-ex0-c-loop.cpp:1:10: fatal error: 'malloc.h' file not found
```

Just drop the include, we already have included `stdlib.h`, which provides malloc

https://stackoverflow.com/questions/56463049/should-mac-osx-have-a-malloc-h-file

2.

```
[ 93%] Building CXX object Intro_Tutorial/lessons/03_umpire_allocator/CMakeFiles/03_umpire_allocator.dir/03_umpire_allocator.cpp.o
[ 94%] Linking CXX executable ../../../bin/03_umpire_allocator
ld: library 'cuda' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Cuda isn't not on, but we have attempt to phantom link cuda.

**Comment by rhornung67** [comment]
I don't see that when I build on LC with gcc 10.3.1. Do you see that error on your Mac?

**Comment by cyrush** [comment]
Just macos :-)
